import productImages from '@/assets/products';
interface IItemProduct {
    id: number,
    orderId?: string;
    image: string;
    name: string;
    marketPrice: number;
    newlyAdded?: boolean,
    store?: string,
    wholesalePrice?: number;
    profit?: number;
  }
export const products:IItemProduct[] = [
    {
        id: 1,
        name: 'Parker Jotter Ballpoint Pen',
        image: productImages.ballpointPen,
        marketPrice: randomNumber(12,14),
        wholesalePrice: randomNumber(8,11),
        newlyAdded: true,
    },
    {
        id: 2,
        name: 'Moleskine Classic Notebook',
        image: productImages.notebook,
        marketPrice: randomNumber(19,22),
        wholesalePrice: randomNumber(9,14),
    },
    {
        id: 3,
        name: 'Deep Moisturizing Biotin Conditioner',
        image: productImages.biotinConditioner,
        marketPrice: randomNumber(13,17),
        wholesalePrice: randomNumber(7,10),
    },
    {
        id: 4,
        name: 'Hybrid Active Noise Cancelling Wireless Earbuds',
        image: productImages.wirelessEarbuds,
        marketPrice: randomNumber(39,49),
        wholesalePrice: randomNumber(25,30),
    },
    {
        id: 5,
        name: 'Multicolor Smart Lamp',
        image: productImages.smartLamp,
        marketPrice: randomNumber(12,18),
        wholesalePrice: randomNumber(8,10),
    },
    {
        id: 6,
        name: 'Waterproof Shower Bluetooth Speaker',
        image: productImages.bluetoothSpeaker,
        marketPrice: randomNumber(12,18),
        wholesalePrice: randomNumber(8,10),
    },
    {
        id: 7,
        name: 'Curling Wand/Hair Waver',
        image: productImages.curlingWandHairWaver,
        marketPrice: randomNumber(18,22),
        wholesalePrice: randomNumber(12,16),
    },
    {
        id: 8,
        name: 'HD Wi-Fi Security Camera',
        image: productImages.hdWiFiSecurityCamera,
        marketPrice: randomNumber(18,22),
        wholesalePrice: randomNumber(12,16),
    },
    {
        id: 9,
        name: "Men's Low Top Sneakers",
        image: productImages.lowTopSneakers,
        marketPrice: randomNumber(80,90),
        wholesalePrice: randomNumber(50,60),
    },
    {
        id: 10,
        name: "Tumbler With Handle 10oz Stainless Steel",
        image: productImages.tumblerWithHandle,
        marketPrice: randomNumber(14,19),
        wholesalePrice: randomNumber(8,11),
    },
    {
        id: 11,
        name: "Crocs Unisex-Adult Classic Clogs",
        image: productImages.crocsUnisex,
        marketPrice: randomNumber(29,39),
        wholesalePrice: randomNumber(18,25),
    },
    {
        id: 12,
        name: "Dove Body Wash with Pump Deep Moisture For Dry Skin",
        image: productImages.doveBodyWash,
        marketPrice: randomNumber(8,10),
        wholesalePrice: randomNumber(5,7),
    },
    {
        id: 13,
        name: "CeraVe Moisturizing Cream",
        image: productImages.CeraVeMoisturizingCream,
        marketPrice: randomNumber(15,18),
        wholesalePrice: randomNumber(10,13),
    },
    {
        id: 14,
        name: "Brita Water Filter for Sink",
        image: productImages.BritaWaterFilter,
        marketPrice: randomNumber(30,35),
        wholesalePrice: randomNumber(20,25),
    },
    {
        id: 15,
        name: "Elecstars Touch Bedside Lamp - with Bluetooth Speaker",
        image: productImages.ElecstarsTouchBedsideLamp,
        marketPrice: randomNumber(20,25),
        wholesalePrice: randomNumber(10,15),
    },
    {
        id: 16,
        name: "SELDORAUK Touch Night Lights for Kids",
        image: productImages.SeldoraukTouchNightLights,
        marketPrice: randomNumber(10,15),
        wholesalePrice: randomNumber(5,9),
    },
    {
        id: 17,
        name: "LilyAna Naturals Retinol Cream",
        image: productImages.LilyAnaNaturalsRetinolCream,
        marketPrice: randomNumber(20,25),
        wholesalePrice: randomNumber(10,15),
    },
    {
        id: 18,
        name: "Portable Charger for iPhone",
        image: productImages.PortableCharger,
        marketPrice: randomNumber(25,30),
        wholesalePrice: randomNumber(15,20),
    },
    {
        id: 19,
        name: "Pfaltzgraff Sadie Dinnerware Set",
        image: productImages.PfaltzgraffSadieDinnerwareSet,
        marketPrice: randomNumber(60,70),
        wholesalePrice: randomNumber(40,50),
    },
    {
        id: 20,
        name: "Century Snack On Folding High Chair",
        image: productImages.CenturySnackOnFolding,
        marketPrice: randomNumber(70,90),
        wholesalePrice: randomNumber(50,60),
    },
    {
        id: 21,
        name: "Small Reindeer Sculpture Resin Christmas",
        image: productImages.SmallReindeerSculptureResinChristmas,
        marketPrice: randomNumber(20,26),
        wholesalePrice: randomNumber(10,15),
    },
    {
        id: 22,
        name: "PETOX Christmas Stockings 18 Inches Large Size",
        image: productImages.ChristmasStockings,
        marketPrice: randomNumber(10,15),
        wholesalePrice: randomNumber(4,7),
    },
    {
        id: 23,
        name: "2 Pack 20 Inches Knit Christmas Stockings",
        image: productImages.KnitChristmasStockings,
        marketPrice: randomNumber(7,10),
        wholesalePrice: randomNumber(3,6),
    },
    {
        id: 24,
        name: "Pre-Lit Christmas Glittering Reindeer with Gold Jingle Bell",
        image: productImages.PreLitChristmasGlitteringReindeer,
        marketPrice: randomNumber(55,65),
        wholesalePrice: randomNumber(35,45),
    },
    {
        id: 25,
        name: "Women's Aubrei Mini Fashion Boot",
        image: productImages.AubreiMiniFashionBoot,
        marketPrice: randomNumber(65,80),
        wholesalePrice: randomNumber(45,55),
    },
    {
        id: 26,
        name: "Fossil Grant Men's Watch with Chronograph Display",
        image: productImages.FossilGrantMensWatch,
        marketPrice: randomNumber(57,64),
        wholesalePrice: randomNumber(41,49),
    },
    {
        id: 27,
        name: "Converse Women's All Star '70s High Top Sneakers",
        image: productImages.ConverseWomensAllStar,
        marketPrice: randomNumber(70,95),
        wholesalePrice: randomNumber(50,65),
    },
    {
        id: 28,
        name: "KitchenAid 9-Speed Digital Hand Mixer with Turbo Beater",
        image: productImages.KitchenAidDigitalHandMixer,
        marketPrice: randomNumber(60,80),
        wholesalePrice: randomNumber(45,55),
    },
]

export const stores = [
    "TrendyTreasures",
    "VirtualVoyages",
    "PixelPalace",
    "E-ShopEmporium",
    "ClickCraze",
    "DigitalDelights",
    "OnlineOasis",
    "CyberChic",
    "ModernMarketplace",
    "WebWonders",
    "E-TailEuphoria",
    "NetNest",
    "InternetInspiration",
    "WebWareHouse",
    "ClicksAndGifts",
    "WebWares",
    "TechTreasures",
    "CyberBoutique",
    "NetNuggets",
    "ClicksAndTrends",
    "DigitalDreams",
    "E-Trends",
    "NetNovelties",
    "VirtualVogue",
    "ByteBazaar",
    "ClickHaven",
    "OnlineOutfitter",
    "NetNiche",
    "CyberSimplicity",
    "E-TailTrinkets",
    "CyberLux",
    "WebWonderland",
    "E-ShopElegance",
    "ClickCrafts",
    "ByteBargains",
    "PixelPicks",
    "OnlineOpulence",
    "VirtualVault",
    "NetNirvana",
    "CyberCharmed",
    "ClicksAndCurios",
    "WebWhimsy",
    "TechTrove",
    "DigitalDesires",
    "CyberConvenience",
    "E-MarketMagic",
    "ClickCrafter",
    "NetNestEgg",
    "E-ShopEssentials",
    "PixelPursuits",
    "WebWaresAndMore",
    "CyberClassics",
    "OnlineOrnaments",
    "ClickCorner",
    "VirtualVariety",
    "NetNifty",
    "WebWondersAndWhims",
    "ClicksAndCollectibles",
    "E-TailExclusives",
    "PixelPleasures",
    "CyberChoices",
    "WebWareFinds",
    "DigitalDeals",
    "ClickChic",
    "VirtualVibrance",
    "NetNeat",
    "CyberClarity",
    "E-ShopSecrets",
    "OnlineOrigins",
    "ClickCurations",
    "TechTreasures",
    "WebWondersEmporium",
    "NetNeon",
    "CyberClutch",
    "ClickCrazeCreations",
    "VirtualVarieties",
    "OnlineOrbits",
    "E-TailTreasures",
    "DigitalDazzle",
    "CyberCrowns",
    "WebWonderEmporium",
    "PixelProspects",
    "NetNook",
    "OnlineOddities",
    "ClickCuriosities",
    "VirtualVista",
    "E-ShopSpectacular",
    "NetNibbles",
    "CyberCharm",
    "WebWaresHub",
    "DigitalDesiresEmporium",
    "E-TailEnchantment",
    "PixelPonder",
    "OnlineOpals",
    "ClickCharmed",
    "NetNovelty",
    "CyberCove",
    "E-ShopEuphoria",
    "WebWonderBoutique",
    "DigitalDarlings",
]

function randomNumber(min: number,max: number) {
    return min + (max-min)*Math.random();
}